[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/api/affirm-authorize"
  to = "/.netlify/functions/affirm-authorize"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
